"questions extracted from opentdb.com - api"
"api :- https://opentdb.com/api.php?amount=10&type=boolean"
question_data = [
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "The name of the main character of the video game &quot;The Legend of Zelda&quot;, is Zelda.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Sports",
     "question": "Wilt Chamberlain scored his infamous 100-point-game against the New York Knicks in 1962.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "Mythology",
     "question": "Rannamaari was a sea demon that haunted the people of the Maldives and had to be appeased monthly "
                 "with the sacrifice of a virgin girl.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Geography",
     "question": "The flag of South Africa features 7 colours.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                                      "question": "Nutella is produced by the German company Ferrero.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Cartoon &amp; Animations",
     "question": "Blue Danube was one of the musical pieces featured in Disney&#039;s 1940&#039;s film Fantasia.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "&quot;Windows NT&quot; is a monolithic kernel.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Cartoon &amp; Animations",
     "question": "Night on Bald Mountain was one of the musical pieces featured in Disney&#039;s 1940&#039;s film Fantasia.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "History",
     "question": "The United States Department of Homeland Security was formed in response to the September 11th attacks.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "Science: Mathematics",
     "question": "If you could fold a piece of paper in half 50 times, its&#039; thickness will be 3\/4th the distance from the Earth to the Sun.",
     "correct_answer": "True", "incorrect_answers": ["False"]}]
